### ISSUE TITLE
Prefer decompyle3 to uncompyle6.

### ISSUE THREAD

**Issue by Caellian** [LuquanLi/TheSims4ScriptModBuilder#1]
[decompyle3](https://pypi.org/project/decompyle3/) is based on [uncompyle6](https://pypi.org/project/uncompyle6/), but targets 3.7 and higher specifically. On linux I couldn't decompile Sims pyc files before switching to decompyle3.

**Comment by LuquanLi** [comment]
Thanks Caellian, I will take a look the decompyle3
